# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  create:
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create gradle sproperties
      run: echo -e "gradle.publish.key=$APIKEY\ngradle.publish.secret=$APISECRET" > $HOME/.gradle/gradle.properties
    - name: Check if Git tag exists
      run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
    - name: Build with Gradle
      run: ./gradlew test build -s --scan
    - name: Runs only if Git tag exists
      run: echo 'A tag name is available"
      if: github.tag != ''
        steps:
          - run: ./gradlew -PrunOnCI=true test build :bintrayUpload :publishPlugins -s --scan